spring:
  profiles:
    active: local

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL:jdbc:h2:mem:test}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}

  sql:
    init:
      mode: ${SQL_INIT_MODE:always}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create}
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: ${JPA_DDI:true}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# aws cloud
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY} # IAM의 Access Key
      secretKey: ${AWS_SECRET_KEY} # IAM의 Secret Key
    region:
      static: ${AWS_REGION:ap-northeast-2} # 환경변수 없으면 기본값 서울 리전
    stack:
      auto: false
    s3:
      bucket: ${AWS_S3_BUCKET} # S3 버킷 이름